#ifndef SKELETON_VERSION_HPP_
#define SKELETON_VERSION_HPP_

// NOLINTNEXTLINE
#define SKELETON_VERSION_MAJOR 0

// NOLINTNEXTLINE
#define SKELETON_VERSION_MINOR 0

// NOLINTNEXTLINE
#define SKELETON_VERSION_PATCH 1

#endif // Include guard
